name: Deply CI

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/settings/tokens
          token: ${{ secrets.DEPLOY_TOKEN }}
          submodules: recursive

      - name: Copy secrets
        shell: bash
        env:
          DOTENV_SECRETS_PATH: ${{ secrets.DOTENV_SECRETS_PATH }}
        run: cp $DOTENV_SECRETS_PATH .env

      - name: Update secrets
        shell: bash
        env:
          DATABASE_VOLUME_PATH: ${{ secrets.DATABASE_VOLUME_PATH }}
          LOGS_VOLUME_PATH: ${{ secrets.LOGS_VOLUME_PATH }}-${{ github.sha }}
          REDIS_VOLUME_PATH: ${{ secrets.REDIS_VOLUME_PATH }}
        run: |
          echo "DATABASE_VOLUME_PATH=$DATABASE_VOLUME_PATH" >> .env
          echo "LOGS_VOLUME_PATH=$LOGS_VOLUME_PATH" >> .env
          echo "REDIS_VOLUME_PATH=$REDIS_VOLUME_PATH" >> .env

      - name: Update secrets
        shell: bash
        env:
          DATABASE_VOLUME_PATH: ${{ secrets.DATABASE_VOLUME_PATH }}
          LOGS_VOLUME_PATH: ${{ secrets.LOGS_VOLUME_PATH }}-${{ github.sha }}
          REDIS_VOLUME_PATH: ${{ secrets.REDIS_VOLUME_PATH }}
        run:
          mkdir $DATABASE_VOLUME_PATH -p
          mkdir $LOGS_VOLUME_PATH -p
          mkdir $REDIS_VOLUME_PATH -p
      
      - name: Build dockers
        shell: bash
        run: docker-compose build

      - name: Run services
        shell: bash
        run: docker-compose up --detach
